package me.gnevilkoko.Enums;

public enum ClickedButton {
    SELECT_SHOP, CHANGE_LANGUAGE, STATISTIC_BUTTON, BACK_BUTTON, SHOW_SHOP_OPINIONS, CREATE_BUY_LIST,
    SELECT_SIMILAR_SHOP, SELECT_SHOP_AS_DEFINED, MORE_OPINIONS, COUNT_PRICES, START_SHOPPING, PRODUCT_MARKING,
    END_BUYING, GO_NEXT_LIST, GO_BACK_LIST, MAKE_RATING, RATING_NUMBER,
    GET_STATS, SELECT_LANGUAGE
}
